# Generated by Django 3.2.5 on 2021-09-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_description_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='text',
            new_name='description',
        ),
    ]
