# Generated by Django 3.2.5 on 2021-09-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_description_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='text',
        ),
    ]
